"""
Stable data-access interface used by every Streamlit page.

WHY THIS FILE EXISTS
---------------------
Today all data is synthetic, generated by src/data_generator.py and stored
in a local SQLite database (see src/database.py). At some point the project
should switch to real telemetry pulled from an API exposed by the actual
field stations.

To make that switch WITHOUT rebuilding the interface, every page imports
only the functions at the bottom of this file (``get_data_source`` and the
module-level convenience wrappers), never src/database.py directly. Those
functions return plain pandas DataFrames with a fixed set of columns
regardless of backend, so pages/*.py never need to know whether the data
came from SQLite or a live API.

TO INTEGRATE A REAL API LATER
------------------------------
1. Implement the ``DataSource`` interface below in ``APIDataSource``
   (methods: get_stations, get_readings, get_latest_readings).
2. Set ``DATA_SOURCE_MODE = "api"`` in config/settings.py (plus whatever
   endpoint/credentials config the real API needs).
3. Nothing in app.py or pages/ needs to change.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Iterable, Optional

import pandas as pd

from config import settings
from src import database


class DataSource(ABC):
    """Interface that any backend (SQLite demo data or a future live API) must implement."""

    @abstractmethod
    def get_stations(self) -> pd.DataFrame:
        """Return station metadata: station_id, name, pair_id, site_type, latitude,
        longitude, elevation_m, description."""

    @abstractmethod
    def get_readings(
        self,
        station_ids: Optional[Iterable[str]] = None,
        start: Optional[str] = None,
        end: Optional[str] = None,
    ) -> pd.DataFrame:
        """Return time-series readings, optionally filtered by station and time window."""

    @abstractmethod
    def get_latest_readings(self) -> pd.DataFrame:
        """Return the single most recent reading for each station."""


class SQLiteDataSource(DataSource):
    """Current implementation: reads the local demonstration database."""

    def get_stations(self) -> pd.DataFrame:
        return database.fetch_stations()

    def get_readings(
        self,
        station_ids: Optional[Iterable[str]] = None,
        start: Optional[str] = None,
        end: Optional[str] = None,
    ) -> pd.DataFrame:
        return database.fetch_readings(station_ids=station_ids, start=start, end=end)

    def get_latest_readings(self) -> pd.DataFrame:
        return database.fetch_latest_readings()


class APIDataSource(DataSource):
    """
    Placeholder for a future connection to real field-station telemetry.

    NOT IMPLEMENTED. No live field station connection exists in this
    prototype. This class exists purely to document the integration point:
    whoever wires up the real monitoring API should implement these three
    methods (matching the return shape of SQLiteDataSource) and flip
    config.settings.DATA_SOURCE_MODE to "api".
    """

    def __init__(self, base_url: Optional[str] = None, api_key: Optional[str] = None):
        self.base_url = base_url
        self.api_key = api_key

    def get_stations(self) -> pd.DataFrame:
        raise NotImplementedError(
            "APIDataSource is a placeholder. Implement a real HTTP call to the "
            "field-station API here, returning the same columns as "
            "SQLiteDataSource.get_stations()."
        )

    def get_readings(
        self,
        station_ids: Optional[Iterable[str]] = None,
        start: Optional[str] = None,
        end: Optional[str] = None,
    ) -> pd.DataFrame:
        raise NotImplementedError(
            "APIDataSource is a placeholder. Implement a real HTTP call to the "
            "field-station API here, returning the same columns as "
            "SQLiteDataSource.get_readings()."
        )

    def get_latest_readings(self) -> pd.DataFrame:
        raise NotImplementedError(
            "APIDataSource is a placeholder. Implement a real HTTP call to the "
            "field-station API here, returning the same columns as "
            "SQLiteDataSource.get_latest_readings()."
        )


def get_data_source() -> DataSource:
    """Factory selecting the active backend based on config.settings.DATA_SOURCE_MODE."""
    if settings.DATA_SOURCE_MODE == "api":
        return APIDataSource()
    return SQLiteDataSource()


# ---------------------------------------------------------------------------
# Convenience module-level wrappers (what pages actually import).
# ---------------------------------------------------------------------------

def get_stations() -> pd.DataFrame:
    return get_data_source().get_stations()


def get_readings(
    station_ids: Optional[Iterable[str]] = None,
    start: Optional[str] = None,
    end: Optional[str] = None,
) -> pd.DataFrame:
    return get_data_source().get_readings(station_ids=station_ids, start=start, end=end)


def get_latest_readings() -> pd.DataFrame:
    return get_data_source().get_latest_readings()
